using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

/// <summary>
/// Summary description for PreData
/// </summary>
public class PreData
{

    public static List<Category> GetCategories()
    {
        return new List<Category> {
            new Category("Fruit"),
            new Category("Animal"),
            new Category("Clothes"),
            new Category("Vegetable"),
            new Category("Flower"),
            new Category("Household"),
            new Category("Electronic"),
            new Category("Smart Phone"),
            new Category("Computer"),
            new Category("Phone Accessory"),
            new Category("Computer Accessory")
        };
    }


    public static List<Country> GetCountries()
    {
        return new List<Country> {
           new Country("Afghanistan"),
            new Country("Albania"),
            new Country("Algeria"),
            new Country("American Samoa"),
            new Country("Andorra"),
            new Country("Angola"),
            new Country("Anguilla"),
            new Country("Antarctica"),
            new Country("Antigua and Barbuda"),
            new Country("Argentina"),
            new Country("Armenia"),
            new Country("Aruba"),
            new Country("Australia"),
            new Country("Austria"),
            new Country("Azerbaijan"),
            new Country("Bahamas"),
            new Country("Bahrain"),
            new Country("Bangladesh"),
            new Country("Barbados"),
            new Country("Belarus"),
            new Country("Belgium"),
            new Country("Belize"),
            new Country("Benin"),
            new Country("Bermuda"),
            new Country("Bhutan"),
            new Country("Bolivia"),
            new Country("Bosnia and Herzegovina"),
            new Country("Botswana"),
            new Country("Bouvet Island"),
            new Country("Brazil"),
            new Country("British Indian Ocean Territory"),
            new Country("Brunei Darussalam"),
            new Country("Bulgaria"),
            new Country("Burkina Faso"),
            new Country("Burundi"),
            new Country("Cambodia"),
            new Country("Cameroon"),
            new Country("Canada"),
            new Country("Cape Verde"),
            new Country("Cayman Islands"),
            new Country("Central African Republic"),
            new Country("Chad"),
            new Country("Chile"),
            new Country("China"),
            new Country("Christmas Island"),
            new Country("Cocos (Keeling) Islands"),
            new Country("Colombia"),
            new Country("Comoros"),
            new Country("Congo"),
            new Country("Congo, the Democratic Republic of the"),
            new Country("Cook Islands"),
            new Country("Costa Rica"),
            new Country("Cote D'Ivoire"),
            new Country("Croatia"),
            new Country("Cuba"),
            new Country("Cyprus"),
            new Country("Czech Republic"),
            new Country("Denmark"),
            new Country("Djibouti"),
            new Country("Dominica"),
            new Country("Dominican Republic"),
            new Country("Ecuador"),
            new Country("Egypt"),
            new Country("El Salvador"),
            new Country("Equatorial Guinea"),
            new Country("Eritrea"),
            new Country("Estonia"),
            new Country("Ethiopia"),
            new Country("Falkland Islands (Malvinas)"),
            new Country("Faroe Islands"),
            new Country("Fiji"),
            new Country("Finland"),
            new Country("France"),
            new Country("French Guiana"),
            new Country("French Polynesia"),
            new Country("French Southern Territories"),
            new Country("Gabon"),
            new Country("Gambia"),
            new Country("Georgia"),
            new Country("Germany"),
            new Country("Ghana"),
            new Country("Gibraltar"),
            new Country("Greece"),
            new Country("Greenland"),
            new Country("Grenada"),
            new Country("Guadeloupe"),
            new Country("Guam"),
            new Country("Guatemala"),
            new Country("Guinea"),
            new Country("Guinea-Bissau"),
            new Country("Guyana"),
            new Country("Haiti"),
            new Country("Heard Island and Mcdonald Islands"),
            new Country("Holy See (Vatican City State)"),
            new Country("Honduras"),
            new Country("Hong Kong"),
            new Country("Hungary"),
            new Country("Iceland"),
            new Country("India"),
            new Country("Indonesia"),
            new Country("Iran, Islamic Republic of"),
            new Country("Iraq"),
            new Country("Ireland"),
            new Country("Israel"),
            new Country("Italy"),
            new Country("Jamaica"),
            new Country("Japan"),
            new Country("Jordan"),
            new Country("Kazakhstan"),
            new Country("Kenya"),
            new Country("Kiribati"),
            new Country("Korea, Democratic People's Republic of"),
            new Country("Korea, Republic of"),
            new Country("Kuwait"),
            new Country("Kyrgyzstan"),
            new Country("Lao People's Democratic Republic"),
            new Country("Latvia"),
            new Country("Lebanon"),
            new Country("Lesotho"),
            new Country("Liberia"),
            new Country("Libyan Arab Jamahiriya"),
            new Country("Liechtenstein"),
            new Country("Lithuania"),
            new Country("Luxembourg"),
            new Country("Macao"),
            new Country("Macedonia, the Former Yugoslav Republic of"),
            new Country("Madagascar"),
            new Country("Malawi"),
            new Country("Malaysia"),
            new Country("Maldives"),
            new Country("Mali"),
            new Country("Malta"),
            new Country("Marshall Islands"),
            new Country("Martinique"),
            new Country("Mauritania"),
            new Country("Mauritius"),
            new Country("Mayotte"),
            new Country("Mexico"),
            new Country("Micronesia, Federated States of"),
            new Country("Moldova, Republic of"),
            new Country("Monaco"),
            new Country("Mongolia"),
            new Country("Montserrat"),
            new Country("Morocco"),
            new Country("Mozambique"),
            new Country("Myanmar"),
            new Country("Namibia"),
            new Country("Nauru"),
            new Country("Nepal"),
            new Country("Netherlands"),
            new Country("Netherlands Antilles"),
            new Country("New Caledonia"),
            new Country("New Zealand"),
            new Country("Nicaragua"),
            new Country("Niger"),
            new Country("Nigeria"),
            new Country("Niue"),
            new Country("Norfolk Island"),
            new Country("Northern Mariana Islands"),
            new Country("Norway"),
            new Country("Oman"),
            new Country("Pakistan"),
            new Country("Palau"),
            new Country("Palestinian Territory, Occupied"),
            new Country("Panama"),
            new Country("Papua New Guinea"),
            new Country("Paraguay"),
            new Country("Peru"),
            new Country("Philippines"),
            new Country("Pitcairn"),
            new Country("Poland"),
            new Country("Portugal"),
            new Country("Puerto Rico"),
            new Country("Qatar"),
            new Country("Reunion"),
            new Country("Romania"),
            new Country("Russian Federation"),
            new Country("Rwanda"),
            new Country("Saint Helena"),
            new Country("Saint Kitts and Nevis"),
            new Country("Saint Lucia"),
            new Country("Saint Pierre and Miquelon"),
            new Country("Saint Vincent and the Grenadines"),
            new Country("Samoa"),
            new Country("San Marino"),
            new Country("Sao Tome and Principe"),
            new Country("Saudi Arabia"),
            new Country("Senegal"),
            new Country("Serbia and Montenegro"),
            new Country("Seychelles"),
            new Country("Sierra Leone"),
            new Country("Singapore"),
            new Country("Slovakia"),
            new Country("Slovenia"),
            new Country("Solomon Islands"),
            new Country("Somalia"),
            new Country("South Africa"),
            new Country("South Georgia and the South Sandwich Islands"),
            new Country("Spain"),
            new Country("Sri Lanka"),
            new Country("Sudan"),
            new Country("Suriname"),
            new Country("Svalbard and Jan Mayen"),
            new Country("Swaziland"),
            new Country("Sweden"),
            new Country("Switzerland"),
            new Country("Syrian Arab Republic"),
            new Country("Taiwan, Province of China"),
            new Country("Tajikistan"),
            new Country("Tanzania, United Republic of"),
            new Country("Thailand"),
            new Country("Timor-Leste"),
            new Country("Togo"),
            new Country("Tokelau"),
            new Country("Tonga"),
            new Country("Trinidad and Tobago"),
            new Country("Tunisia"),
            new Country("Turkey"),
            new Country("Turkmenistan"),
            new Country("Turks and Caicos Islands"),
            new Country("Tuvalu"),
            new Country("Uganda"),
            new Country("Ukraine"),
            new Country("United Arab Emirates"),
            new Country("United Kingdom"),
            new Country("United States"),
            new Country("United States Minor Outlying Islands"),
            new Country("Uruguay"),
            new Country("Uzbekistan"),
            new Country("Vanuatu"),
            new Country("Venezuela"),
            new Country("Viet Nam"),
            new Country("Virgin Islands, British"),
            new Country("Virgin Islands, US"),
            new Country("Wallis and Futuna"),
            new Country("Western Sahara"),
            new Country("Yemen"),
            new Country("Zambia"),
            new Country("Zimbabwe")
            };
    }


}